### ISSUE TITLE
sync-external-contributions: command not found

### ISSUE THREAD

**Issue by maximbetin** [charpeni/sync-external-contributions#2]
Pretty much title. Every time I try to run `sync-external-contributions` I get `sync-external-contributions: command not found`. Tried on two different machines. What am I doing wrong? I do have git-standup installed as well.

**Comment by m00nb0w** [comment]
I'm having the same error. I'm using MacOs with fish.

**Comment by charpeni** [comment]
This is fixed in `v1.2.1`. You can now use this with npx: `npx sync-external-contributions`.
